### ISSUE TITLE
Add option to change color of controllers

### ISSUE THREAD

**Issue by bkhezry** [nainemom/sausage#1]
Controllers of the video did not show in light background videos. Please add an option to select colors for them.
Screenshot:

![photo5870988417393866719](https://user-images.githubusercontent.com/91809/119729731-3e01c600-be8a-11eb-9491-39337b3293c3.jpg)

**Comment by nainemom** [comment]
I'ts complicated to add this "change colors" feature for now (as it need add more option to settings page), but the issue is still valid. So I just updated the background colors of buttons and now it should be works well.
https://github.com/nainemom/sausage/releases/tag/v0.0.2
